server:
  port: 8081
spring:
  application:
    name: supermarket-chain-management
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&useUnicode=true
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: SupermarketHikariPool
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 0
    host: 127.0.0.1        # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000
  #  这个mvc的配置是springboot2.6.1不支持swagger3的折衷配置，后面考虑升级Springboot版本或降级版本
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cqupt.th.supermarket.entity
